apiVersion: batch/v1
kind: Job
metadata:
  name: gas-model-eval
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: eval
          image: gas-m1:0.1            # your local tag
          imagePullPolicy: Never       # capitalize N
          command: ["python", "evaluate_models.py"]
